# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\static\QtUI\downloader.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 290)
        font = QtGui.QFont()
        font.setFamily("Museo Sans Cyrl 500")
        font.setPointSize(14)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_name = QtWidgets.QLabel(self.centralwidget)
        self.label_name.setGeometry(QtCore.QRect(10, 30, 780, 50))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setBold(True)
        font.setWeight(75)
        self.label_name.setFont(font)
        self.label_name.setTextFormat(QtCore.Qt.AutoText)
        self.label_name.setAlignment(QtCore.Qt.AlignCenter)
        self.label_name.setObjectName("label_name")
        self.label_patch = QtWidgets.QLabel(self.centralwidget)
        self.label_patch.setGeometry(QtCore.QRect(20, 100, 260, 40))
        self.label_patch.setObjectName("label_patch")
        self.lineEdit_patch = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_patch.setGeometry(QtCore.QRect(290, 100, 490, 40))
        self.lineEdit_patch.setObjectName("lineEdit_patch")
        self.pushButton_create = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_create.setGeometry(QtCore.QRect(20, 160, 760, 40))
        self.pushButton_create.setObjectName("pushButton_create")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 800, 25))
        self.menuBar.setObjectName("menuBar")
        self.menu_about = QtWidgets.QMenu(self.menuBar)
        font = QtGui.QFont()
        font.setFamily("Museo Sans Cyrl 500")
        self.menu_about.setFont(font)
        self.menu_about.setObjectName("menu_about")
        self.menu_preferences = QtWidgets.QMenu(self.menuBar)
        font = QtGui.QFont()
        font.setFamily("Museo Sans Cyrl 500")
        self.menu_preferences.setFont(font)
        self.menu_preferences.setObjectName("menu_preferences")
        self.menu_theme = QtWidgets.QMenu(self.menu_preferences)
        font = QtGui.QFont()
        font.setFamily("Museo Sans Cyrl 500")
        self.menu_theme.setFont(font)
        self.menu_theme.setObjectName("menu_theme")
        MainWindow.setMenuBar(self.menuBar)
        self.action_app = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Museo Sans Cyrl 500")
        self.action_app.setFont(font)
        self.action_app.setObjectName("action_app")
        self.action_author = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Museo Sans Cyrl 500")
        self.action_author.setFont(font)
        self.action_author.setObjectName("action_author")
        self.action_theme_light = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Museo Sans Cyrl 500")
        self.action_theme_light.setFont(font)
        self.action_theme_light.setObjectName("action_theme_light")
        self.action_theme_dark = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Museo Sans Cyrl 500")
        self.action_theme_dark.setFont(font)
        self.action_theme_dark.setObjectName("action_theme_dark")
        self.menu_about.addAction(self.action_app)
        self.menu_about.addAction(self.action_author)
        self.menu_theme.addAction(self.action_theme_light)
        self.menu_theme.addAction(self.action_theme_dark)
        self.menu_preferences.addAction(self.menu_theme.menuAction())
        self.menuBar.addAction(self.menu_about.menuAction())
        self.menuBar.addAction(self.menu_preferences.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Dota 2 Patch Download Script Generator"))
        self.label_name.setText(_translate("MainWindow", "Автоподбор манифестов для скрипта загрузки старых патчей Dota 2"))
        self.label_patch.setText(_translate("MainWindow", "Ссылка на патч (SteamDB):"))
        self.pushButton_create.setText(_translate("MainWindow", "Создать скрипт"))
        self.menu_about.setTitle(_translate("MainWindow", "Подробнее"))
        self.menu_preferences.setTitle(_translate("MainWindow", "Настройки"))
        self.menu_theme.setTitle(_translate("MainWindow", "Тема"))
        self.action_app.setText(_translate("MainWindow", "О приложении"))
        self.action_author.setText(_translate("MainWindow", "Об авторе"))
        self.action_theme_light.setText(_translate("MainWindow", "Светлая"))
        self.action_theme_dark.setText(_translate("MainWindow", "Темная"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
